all: install

install:
    go install ./...

build:
	go build ./...

build-all:
	GOOS=linux GOARCH=amd64 go build -o build/linux/mhosts ./...
	GOOS=darwin GOARCH=amd64 go build -o build/darwin/mhosts ./...
	GOOS=windows GOARCH=amd64 go build -o build/windows/mhosts.exe ./...
